const roomsData = [
  {
    propertyid: '1982',
    room_id: '152862',
    room_text: 'Standard Room',
    rate_id: '1',
    rate_text: 'Basic Rate',
    data: [
      {
        date: '2019-09-30',
        inventory: '3',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'Y',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-01',
        inventory: '3',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'Y',
        ctd: 'N',
      },
      {
        date: '2019-10-02',
        inventory: '3',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-03',
        inventory: '3',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-04',
        inventory: '3',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-05',
        inventory: '3',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-06',
        inventory: '3',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-07',
        inventory: '3',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-08',
        inventory: '3',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-09',
        inventory: '3',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-10',
        inventory: '3',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-11',
        inventory: '3',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-12',
        inventory: '3',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-13',
        inventory: '5',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-14',
        inventory: '5',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-15',
        inventory: '5',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-16',
        inventory: '5',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-17',
        inventory: '5',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-18',
        inventory: '5',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-19',
        inventory: '5',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-20',
        inventory: '5',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
    ],
  },
  {
    propertyid: '1982',
    room_id: '152862',
    room_text: 'Standard Room',
    rate_id: '2',
    rate_text: 'Basic With Breakfast',
    data: [
      {
        date: '2019-09-30',
        inventory: '3',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-01',
        inventory: '3',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'Y',
      },
      {
        date: '2019-10-02',
        inventory: '3',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-03',
        inventory: '3',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-04',
        inventory: '3',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-05',
        inventory: '3',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-06',
        inventory: '3',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-07',
        inventory: '3',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-08',
        inventory: '3',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-09',
        inventory: '3',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-10',
        inventory: '3',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-11',
        inventory: '3',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-12',
        inventory: '3',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-13',
        inventory: '5',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-14',
        inventory: '5',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-15',
        inventory: '5',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-16',
        inventory: '5',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-17',
        inventory: '5',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-18',
        inventory: '5',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-19',
        inventory: '5',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-20',
        inventory: '5',
        currency: 'NZD',
        rate: '2,050',
        obp: {
          person1: '2,050',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
    ],
  },
  {
    propertyid: '1982',
    room_id: '152862',
    room_text: 'Standard Room',
    rate_id: '3',
    rate_text: 'Non-Refundable',
    data: [
      {
        date: '2019-09-30',
        inventory: '3',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'Y',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-01',
        inventory: '3',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'Y',
        ctd: 'N',
      },
      {
        date: '2019-10-02',
        inventory: '3',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-03',
        inventory: '3',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-04',
        inventory: '3',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-05',
        inventory: '3',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-06',
        inventory: '3',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-07',
        inventory: '3',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-08',
        inventory: '3',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-09',
        inventory: '3',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-10',
        inventory: '3',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-11',
        inventory: '3',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-12',
        inventory: '3',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-13',
        inventory: '5',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-14',
        inventory: '5',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-15',
        inventory: '5',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-16',
        inventory: '5',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-17',
        inventory: '5',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-18',
        inventory: '5',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-19',
        inventory: '5',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-10-20',
        inventory: '5',
        currency: 'NZD',
        rate: '1,900',
        obp: {
          person1: '1,900',
          person2: '2,050',
          person3: '2,100',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
    ],
  },

  {
    propertyid: '1982',
    room_id: '152863',
    room_text: 'Delux Room',
    rate_id: '01',
    rate_text: 'Basic rate',
    data: [
      {
        date: '2019-07-27',
        inventory: '6',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,250',
          person3: '2300',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-07-28',
        inventory: '6',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,250',
          person3: '2300',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-07-29',
        inventory: '6',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,250',
          person3: '2300',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-07-30',
        inventory: '6',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,250',
          person3: '2300',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-07-31',
        inventory: '9',
        currency: 'NZD',
        rate: '2,000',
        obp: {
          person1: '2,000',
          person2: '2,250',
          person3: '2300',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
    ],
  },
  {
    propertyid: '1982',
    room_id: '152863',
    room_text: 'Delux Room',
    rate_id: '02',
    rate_text: 'Basic With Breakfast',
    data: [
      {
        date: '2019-07-27',
        inventory: '6',
        currency: 'NZD',
        rate: '2,250',
        obp: {
          person1: '2,250',
          person2: '2300',
          person3: '2350',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-07-28',
        inventory: '6',
        currency: 'NZD',
        rate: '2,250',
        obp: {
          person1: '2,250',
          person2: '2300',
          person3: '2350',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-07-29',
        inventory: '6',
        currency: 'NZD',
        rate: '2,250',
        obp: {
          person1: '2,250',
          person2: '2300',
          person3: '2350',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-07-30',
        inventory: '6',
        currency: 'NZD',
        rate: '2,250',
        obp: {
          person1: '2,250',
          person2: '2300',
          person3: '2350',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
      {
        date: '2019-07-31',
        inventory: '9',
        currency: 'NZD',
        rate: '2,250',
        obp: {
          person1: '2,250',
          person2: '2300',
          person3: '2350',
        },
        extraadult: '50',
        extrachild: '50',
        stopsell: 'N',
        minstay: '2',
        maxstay: '27',
        cta: 'N',
        ctd: 'N',
      },
    ],
  },
];
export default roomsData;
